# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/kinetics/val_joints.npy
  label_path: ./data/kinetics/val_labels.pkl
  debug: False

# model
model: model.stbln.STBLN
model_args:
  num_class: 400
  num_person: 2
  num_point: 18


# test 
phase: test
device: 0
test_batch_size: 1
weights: ./pretrained_models/stbln/stbln_kinetics_joint-64-122070.pt


work_dir: ./work_dir/kinetics/stbln_joint_test
model_saved_name: ./runs/ki_stbln_joint_test
save_score: False