work_dir: ./work_dir/kinetics/stbln_bone
model_saved_name: ./runs/stbln/ki_stbln_bone

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ../data/kinetics/train_data_bone.npy
  label_path: ../data/kinetics/train_label.pkl
  debug: False

test_feeder_args:
  data_path: ../data/kinetics/val_data_bone.npy
  label_path: ../data/kinetics/val_label.pkl

# model
model: model.stbln.STBLN
model_args:
  num_class: 400
  num_person: 2
  num_point: 18
  symmetric: False

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [45, 55]

# training
device: [4,5,6,7]
batch_size: 128
test_batch_size: 256
num_epoch: 65
nesterov: True




