# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/nturgbd_cv/val_joints.npy
  label_path: ./data/nturgbd_cv/val_labels.pkl
  debug: False

# model
model: model.stbln.STBLN
model_args:
  num_class: 60
  num_point: 25
  num_person: 2

# test
phase: test
device: 0
test_batch_size: 1
weights: ./pretrained_models/stbln/stbln_nturgbd_cv_joint-49-29400/stbln_nturgbd_cv_joint-49-29400.pt

work_dir: ./work_dir/ntu/xsub/agcn_test_joint
model_saved_name: ./runs/ntu_cs_agcn_test_joint
save_score: False