work_dir: ./work_dir/kinetics/pstbln_bone
model_saved_name: ./runs/pstbln/ki_pstgcn_bone
results_file_name: pstbln_kinetics_bone_results.txt
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../../data/kinetics/train_data_bone.npy
  label_path: ../../data/kinetics/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../../data/kinetics/val_data_bone.npy
  label_path: ../../data/kinetics/val_label.pkl

# model
model: model.pstbln.PSTBLN
model_name: pstbln
model_args:
  num_class: 400
  num_point: 18
  num_person: 2
  in_channels: 3
  topology: []
  blocksize: 20

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [45, 55]

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 128
num_epoch: 65
nesterov: True
