# it needs to be modified for pstbln

# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/nturgbd_cv/val_joints.npy
  label_path: ./data/nturgbd_cv/val_labels.pkl
  debug: False

# model
model: model.pstbln.PSTBLN
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  topology: [5,4,5,2,3,4,3,4]
  block_size: 20

# test
phase: test
device: 0
test_batch_size: 10
weights: ./pretrained_models/pstbln/ntu_cv_pstbln_joint-8-4/ntu_cv_pstbln_joint-8-4.pt

work_dir: ./work_dir/ntu/xsub/pstbln_test_joint
model_saved_name: ./runs/ntu_cv_pstbln_test_joint
save_score: False