work_dir: ./work_dir/ntu/xview/pstbln_joint
model_saved_name: ./runs/pstbln/ntu_cv_pstbln_joint
results_file_name: pstbln_ntu_cv_joint_results.txt
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ../../data/ntu/xview/train_data_joint.npy
  label_path: ../../data/ntu/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../../data/ntu/xview/val_data_joint.npy
  label_path: ../../data/ntu/xview/val_label.pkl

# model
model: model.pstbln.PSTBLN
model_name: pstbln
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  in_channels: 3
  topology: []
  blocksize: 20

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 128
num_epoch: 50
nesterov: True
